version: 2.1
orbs:
  terraform: circleci/terraform@3.2.0
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/init:
          context: Terraform
          path: .
      - terraform/fmt:
          checkout: true
          context: Terraform
      - terraform/validate:
          checkout: true
          context: Terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: Terraform
          path: terraform
          persist-workspace: true
          var_file : prod.tfvars
          requires:
            - terraform/validate
      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: test
          requires:
            - terraform/plan